# Generated by Django 3.0.3 on 2020-02-11 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='conent',
            new_name='content',
        ),
    ]
