# Generated by Django 3.0.3 on 2020-02-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_auto_20200211_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('papier', 'papier'), ('metale_plastik', 'metale_plastik'), ('szko', 'szko'), ('bio', 'bio'), ('zmieszane', 'zmieszane')], max_length=20),
        ),
    ]
